name: 更新json

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:
    分支:
      - main    

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run py
       run: |
          python ${{ github.workspace }}/py/更新json.py  

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add.
        git commit -m "Automated update by GitHub Action"
        git push
